language: rust
rust:
  - stable
  # - beta
  # - nightly
cache: cargo
# jobs:
#   allow_failures:
#     - rust: nightly
#   fast_finish: true
script:
  # - cargo build --verbose --all-targets
  - cargo build --all-targets
  # - cargo test --verbose --all
  - cargo test --all